apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tkn-go-github-test-4 
  janus-idp.io/tekton: tkn-go-github-test-4
  backstage.io/kubernetes-id: tkn-go-github-test-4
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tkn-go-github-test-4
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  