apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: testing-development
spec:
  params:
  - description: Gitops repo url
    name: git-url
    type: string
  - default: ""
    description: Gitops repo revision
    name: revision
    type: string
  tasks:
  - name: clone-repository
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    - name: fetchTags
      value: "true"
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
    - name: basic-auth
      workspace: git-auth

  - name: test-image
    runAfter:
    - clone-repository
    params: []
    workspaces:
    - name: source
      workspace: workspace
    taskSpec:
      params:
      - name: SIGNING_SECRET_NAME
        descripiton: >
          Name of the k9s Secret containing the sigstore signing key to be used when creating the
          test attestation.
        default: test-signing
      volumes:
      - name: signing-key
        secret:
          optional: true
          secretName: $(params.SIGNING_SECRET_NAME)
      stepTemplate:
        env:
        - name: HOME
          value: /tekton/home
        volumeMounts:
        - mountPath: /etc/secrets
          name: signing-key
          readOnly: true
      steps:
      - command:
        - ./hack/test-development-image.sh
        - /etc/secrets
        image: registry.access.redhat.com/rhtap-task-runner/rhtap-task-runner-rhel9:1.5
        name: test
        workingDir: $(workspaces.source.path)/source
