apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tkn-go-github-test-4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tkn-go-github-test-4 
  name: tkn-go-github-test-4
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tkn-go-github-test-4 
